# Generated by Django 5.0.6 on 2024-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Contraseña', models.CharField(max_length=255)),
            ],
        ),
    ]
